import 'dart:io';
import 'package:pdf/pdf.dart';
import 'package:pdf/widgets.dart' as pw;
import 'package:printing/printing.dart';
import '../models/evidence.dart';

class LegalReportService {

  static Future<void> generateReport(Evidence evidence) async {

    final pdf = pw.Document();

    pdf.addPage(
      pw.MultiPage(
        build: (context) => [

          pw.Text(
            "DIGITAL EVIDENCE REPORT",
            style: pw.TextStyle(
              fontSize: 22,
              fontWeight: pw.FontWeight.bold,
            ),
          ),

          pw.SizedBox(height: 20),

          pw.Text("Evidence ID: ${evidence.evidenceId}"),
          pw.Text("Captured At: ${evidence.timestamp}"),

          pw.SizedBox(height: 15),

          pw.Text(
            "SHA-256 HASH",
            style: pw.TextStyle(fontWeight: pw.FontWeight.bold),
          ),
          pw.Text(evidence.hash),

          pw.SizedBox(height: 25),

          pw.Text(
            "CHAIN OF CUSTODY",
            style: pw.TextStyle(
              fontSize: 16,
              fontWeight: pw.FontWeight.bold,
            ),
          ),

          ...evidence.custody.map(
            (c) => pw.Text("${c.event} — ${c.time}"),
          ),

          pw.SizedBox(height: 30),

          // =========================
          // SECTION 65B CERTIFICATE
          // =========================
          pw.Text(
            "SECTION 65B CERTIFICATE",
            style: pw.TextStyle(
              fontSize: 16,
              fontWeight: pw.FontWeight.bold,
            ),
          ),

          pw.SizedBox(height: 10),

          pw.Text(
            """
I hereby certify under Section 65B of the Indian Evidence Act, 1872, 
that the electronic record presented above was produced by a secure 
digital system operating in the ordinary course of activities.

The data was automatically recorded, hashed using SHA-256, and stored 
without alteration. The integrity verification confirms that the 
electronic evidence remains authentic and untampered.

This certificate is generated electronically by Sakshi Vault.
            """,
          ),

          pw.SizedBox(height: 40),

          pw.Text("Generated By: Sakshi Vault"),
          pw.Text("Date: ${DateTime.now()}"),
        ],
      ),
    );

    // Open preview / print / save
    await Printing.layoutPdf(
      onLayout: (format) async => pdf.save(),
    );
  }
}